Make CopyProp and DS2CPS handle loops
AnyDSL/thorin2 pull request #62
Opened 2022-07-15 10:52 UTC by fodinabor

CopyProp and DS2CPS both currently either bail or fail if a loop matches their patterns.

CopyProp needed to be extended to explicitly work on branches `(f, t)#cond (args, ...)` instead of just directly applied non lams.

DS2CPS just died of a stack overflow due to infinitely following the loop recursion.
DS2CPS should generally be a bit more stable now.
One major downside of this change is, that when having a loop, we must not set the PE filter to true, but without doing so, we introduce some unnecessary overhead for the non-loop cases.
Note, the loop support greatly depends on copyprop being able to propagate the continuations through branches.

2022-07-17 22:26 UTC, leissa commented
This looks overly complicated to me. 

> CopyProp needed to be extended to explicitly work on branches `(f, t)#cond (args, ...)` instead of just directly applied non lams.

IMHO only dealing with directly applied nom lams is enough due to the EtaExp - which makes this whole `CopyProp::rewrite_conditional` stuff superfluous. Maybe there is another problem with the EtaExp or its interaction with the CopyProp.

2022-07-18 16:14 UTC, leissa requested changes
The DS2CPS changes look pretty solid to me, but I had a concern regarding the CopyProp (see above).

2022-07-20 09:10 UTC, fodinabor commented
The `lit/main_loop_cn.thorin` test case fails for master, but is supported by this branch. The main issue here is that the continuations have to be fully removed for the ll backend to be happy. Afaict, EtaExp would not get rid of those parameters. LamSpec does not support this either and would be complicated to adapt to it (as an RWPass) and for the cases that I came up with, CopyProp seemed to be able to solve these situations by propagating through the branch as well.

I'm currently still investigating an issue with the CopyProp, though (calling the loop from the test case twice - once from main, once from the exit continuation).

2022-07-25 09:48 UTC, fodinabor commented
I removed the CopyProp changes from this PR. I currently don't see a straightforward way to avoid that DS2CPS generates a loop where all lams have a continuation. The input for the CopyProp was already Eta reduced, which made it pretty clean.

I've been considering adding an extra PM phase so we can use the CopyProp changes without it fighting against the Beta reduction, as it currently does for some cases, but that would again require tighter coupling from the `optimize` function to the plugins since CopyProp is in the mem dialect. Before I do that, I'm wondering whether we might want to generalize the pass registration further:
I could imagine that it'd make sense to have a map similar to the backends map that is currently used for the `ll` backend. This map is filled by the plugins with `pass->name()` -> `<Pass>* thorin_add_<dialect>_<pass>(PassMan& pass)`.
This has two benefits:
- we can write textual descriptions of the pass pipeline, we want to use (think LLVM's new `opt --passes="function(<pass>,<pass>)"` syntax, where `()` can be used to group passes together into a PM.
- we can more easily build up a custom pipeline in frontend X, since we just load all plugins we need, and don't have to ask `dlsym` for the creation functions, but instead can query the map directly with the passes' name.

Thoughts?

2022-07-28 10:10 UTC, leissa commented
I'll merge for now. We can discuss your other points next time in our online meeting :)

2022-07-28 10:10 UTC, merged